import os
import json
from pathlib import Path

WORKSPACE = Path(r"C:\Users\akhil\.gemini\antigravity\scratch")
BACKEND = WORKSPACE / "backend"
FRONTEND = WORKSPACE / "frontend"
SRC = FRONTEND / "src"
COMPONENTS = SRC / "components"
DATA = WORKSPACE / "data"

for d in [BACKEND, FRONTEND, SRC, COMPONENTS, DATA]:
    d.mkdir(parents=True, exist_ok=True)

# -------------------------------------------------------------
# 1. backend/__init__.py
# -------------------------------------------------------------
(BACKEND / "__init__.py").write_text('"""TripTrail NATPAC Backend Package"""\n', encoding="utf-8")

# -------------------------------------------------------------
# 2. backend/database.py
# -------------------------------------------------------------
db_lines = [
    'import os',
    'import json',
    'import sqlite3',
    'from datetime import datetime',
    'from pathlib import Path',
    'from typing import Any, Dict, List, Optional, Tuple',
    '',
    'DB_DIR = Path(__file__).resolve().parent.parent / "data"',
    'DB_DIR.mkdir(parents=True, exist_ok=True)',
    'SQLITE_PATH = DB_DIR / "triptrail.db"',
    'DATABASE_URL = os.getenv("DATABASE_URL")',
    '',
    'def get_connection():',
    '    conn = sqlite3.connect(str(SQLITE_PATH), timeout=15.0, check_same_thread=False)',
    '    conn.row_factory = sqlite3.Row',
    '    conn.execute("PRAGMA journal_mode = WAL;")',
    '    conn.execute("PRAGMA foreign_keys = ON;")',
    '    return conn',
    '',
    'def init_db():',
    '    with get_connection() as conn:',
    '        cursor = conn.cursor()',
    '        cursor.execute("""',
    '            CREATE TABLE IF NOT EXISTS trips (',
    '                id INTEGER PRIMARY KEY AUTOINCREMENT,',
    '                title TEXT NOT NULL,',
    '                location TEXT NOT NULL,',
    '                start_date TEXT NOT NULL,',
    '                end_date TEXT NOT NULL,',
    '                note TEXT DEFAULT "",',
    '                mood TEXT DEFAULT "sunny",',
    '                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,',
    '                trip_number INTEGER DEFAULT 1,',
    '                origin TEXT DEFAULT "",',
    '                destination TEXT DEFAULT "",',
    '                departure_time TEXT DEFAULT "",',
    '                arrival_time TEXT DEFAULT "",',
    '                travel_mode TEXT DEFAULT "Bus",',
    '                trip_purpose TEXT DEFAULT "Tourism",',
    '                passenger_count INTEGER DEFAULT 1,',
    '                fare_cost REAL DEFAULT 0.0,',
    '                distance_km REAL DEFAULT 0.0,',
    '                duration_min INTEGER DEFAULT 0,',
    '                origin_lat REAL,',
    '                origin_lng REAL,',
    '                dest_lat REAL,',
    '                dest_lng REAL,',
    '                is_auto_detected INTEGER DEFAULT 0,',
    '                is_synced INTEGER DEFAULT 1,',
    '                gps_trace_json TEXT DEFAULT "[]"',
    '            );',
    '        """)',
    '        cursor.execute("""',
    '            CREATE TABLE IF NOT EXISTS destinations (',
    '                id INTEGER PRIMARY KEY AUTOINCREMENT,',
    '                name TEXT UNIQUE NOT NULL,',
    '                state_region TEXT DEFAULT "Kerala",',
    '                category TEXT DEFAULT "Tourism",',
    '                description TEXT DEFAULT "",',
    '                latitude REAL DEFAULT 0.0,',
    '                longitude REAL DEFAULT 0.0,',
    '                food_cuisine TEXT DEFAULT "[]",',
    '                attractions TEXT DEFAULT "[]",',
    '                hotels TEXT DEFAULT "[]",',
    '                activities TEXT DEFAULT "[]",',
    '                ratings REAL DEFAULT 4.5,',
    '                approx_cost_per_day REAL DEFAULT 2000.0,',
    '                best_season TEXT DEFAULT "Oct - Mar",',
    '                weather_summary TEXT DEFAULT "Pleasant",',
    '                image_url TEXT DEFAULT "",',
    '                source TEXT DEFAULT "local_cache",',
    '                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP',
    '            );',
    '        """)',
    '        cursor.execute("""',
    '            CREATE TABLE IF NOT EXISTS natpac_surveys (',
    '                id INTEGER PRIMARY KEY AUTOINCREMENT,',
    '                user_id TEXT DEFAULT "anonymous",',
    '                age_group TEXT DEFAULT "18-35",',
    '                gender TEXT DEFAULT "Unspecified",',
    '                occupation TEXT DEFAULT "Working Professional",',
    '                monthly_travel_budget REAL DEFAULT 3000.0,',
    '                frequent_mode TEXT DEFAULT "Bus / Public Transport",',
    '                feedback TEXT DEFAULT "",',
    '                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP',
    '            );',
    '        """)',
    '        cursor.execute("""',
    '            CREATE TABLE IF NOT EXISTS tourism_cache (',
    '                cache_key TEXT PRIMARY KEY,',
    '                data_json TEXT NOT NULL,',
    '                cached_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,',
    '                expires_at TEXT',
    '            );',
    '        """)',
    '        cursor.execute("CREATE INDEX IF NOT EXISTS idx_trips_start_date ON trips(start_date DESC);")',
    '        cursor.execute("CREATE INDEX IF NOT EXISTS idx_trips_mode ON trips(travel_mode);")',
    '        cursor.execute("CREATE INDEX IF NOT EXISTS idx_destinations_name ON destinations(name);")',
    '        cursor.execute("CREATE INDEX IF NOT EXISTS idx_destinations_region ON destinations(state_region);")',
    '        conn.commit()',
    '        seed_destinations_if_empty(cursor, conn)',
    '        seed_sample_trips_if_empty(cursor, conn)',
    '',
    'def seed_destinations_if_empty(cursor, conn):',
    '    cursor.execute("SELECT COUNT(*) as cnt FROM destinations;")',
    '    if cursor.fetchone()["cnt"] > 0:',
    '        return',
    '    sample_destinations = [',
    '        {',
    '            "name": "Munnar",',
    '            "state_region": "Kerala (Idukki)",',
    '            "category": "Hill Station & Tea Plantations",',
    '            "description": "Munnar is a picturesque hill station in the Western Ghats known for lush tea estates, misty valleys, waterfalls, and rare flora like Neelakurinji.",',
    '            "latitude": 10.0889,',
    '            "longitude": 77.0595,',
    '            "food_cuisine": json.dumps(["Kerala Parotta with Veg/Chicken Curry", "Puttu and Kadala Curry", "Fresh Cardamom & Ginger Tea", "Spiced Hot Banana Fritters (Pazham Pori)", "Local Roasted Cashews & Homemade Chocolates"]),',
    '            "attractions": json.dumps(["Eravikulam National Park (Nilgiri Tahr sanctuary)", "Mattupetty Dam & Eco Point", "Tea Museum & Tata Tea Estate", "Top Station Panorama Viewpoint", "Attukad & Lakkam Waterfalls"]),',
    '            "hotels": json.dumps([{"name": "Tea County Munnar (KTDC)", "type": "Heritage / Mid-Range", "price_range": "₹4,500 - ₹7,000/night", "rating": 4.6}, {"name": "Blanket Hotel & Spa", "type": "Luxury Resort", "price_range": "₹9,000 - ₹15,000/night", "rating": 4.8}, {"name": "Munnar Green Homestay", "type": "Budget Homestay", "price_range": "₹1,500 - ₹2,500/night", "rating": 4.4}]),',
    '            "activities": json.dumps(["Tea Plantation Trekking & Estate Tour", "Nilgiri Tahr Wildlife Safari", "Boating at Mattupetty Reservoir", "Campfire & Stargazing at Top Station", "Spice Plantation Walk & Ayurvedic Massage"]),',
    '            "ratings": 4.8,',
    '            "approx_cost_per_day": 3200.0,',
    '            "best_season": "September to March",',
    '            "weather_summary": "Misty, Cool & Pleasant (15°C - 24°C)",',
    '            "image_url": "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&auto=format&fit=crop&q=80",',
    '            "source": "local_cache"',
    '        },',
    '        {',
    '            "name": "Kochi (Cochin)",',
    '            "state_region": "Kerala (Ernakulam)",',
    '            "category": "Coastal & Heritage Port",',
    '            "description": "The Queen of the Arabian Sea, blending Portuguese, Dutch, British colonial history with Chinese fishing nets, vibrant spice markets, and modern Kochi Metro.",',
    '            "latitude": 9.9312,',
    '            "longitude": 76.2673,',
    '            "food_cuisine": json.dumps(["Karimeen Pollichathu (Pearl Spot Fish in Banana Leaf)", "Kerala Fish Curry Meals", "Appam with Stew (Chicken/Veg)", "Mattancherry Biryani & Kayees Delicacy", "Kuluki Sarbath & Fresh Tender Coconut"]),',
    '            "attractions": json.dumps(["Fort Kochi Chinese Fishing Nets", "Mattancherry Palace (Dutch Palace)", "Jewish Synagogue & Jew Town", "St. Francis Church (Vasco da Gama memorial)", "Marine Drive & Kochi Water Metro Ferry"]),',
    '            "hotels": json.dumps([{"name": "Brunton Boatyard - CGH Earth", "type": "Luxury Heritage", "price_range": "₹14,000 - ₹22,000/night", "rating": 4.9}, {"name": "Old Harbour Hotel", "type": "Boutique Hotel", "price_range": "₹7,500 - ₹12,000/night", "rating": 4.7}, {"name": "Zostel Kochi (Fort Kochi)", "type": "Backpacker Hostel", "price_range": "₹800 - ₹2,000/night", "rating": 4.5}]),',
    '            "activities": json.dumps(["Kathakali Dance Performance at Kerala Kathakali Centre", "Kochi Water Metro Ride across islands", "Heritage Walking Tour in Fort Kochi", "Spice Market Shopping at Jew Town", "Sunset Cruise on Cochin Harbour"]),',
    '            "ratings": 4.7,',
    '            "approx_cost_per_day": 2800.0,',
    '            "best_season": "October to April",',
    '            "weather_summary": "Warm & Coastal Breeze (25°C - 31°C)",',
    '            "image_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80",',
    '            "source": "local_cache"',
    '        },',
    '        {',
    '            "name": "Alappuzha (Alleppey)",',
    '            "state_region": "Kerala (Alappuzha)",',
    '            "category": "Backwaters & Coastal",',
    '            "description": "Venice of the East, world-famous for its tranquil backwaters, traditional Kettuvallam houseboats, coir crafts, paddy fields below sea level (Kuttanad), and beach pier.",',
    '            "latitude": 9.4981,',
    '            "longitude": 76.3388,',
    '            "food_cuisine": json.dumps(["Kuttanadan Duck Roast (Tharavu Roast)", "Fresh Backwater Prawn Roast (Konchu)", "Karimeen Fry with Tapioca (Kappa & Meen Curry)", "Traditional Kerala Sadya on Plantain Leaf", "Toddy Shop Delicacies & Fresh Clam Fry"]),',
    '            "attractions": json.dumps(["Punnamada Lake (Nehru Trophy Boat Race venue)", "Vembanad Lake Backwater Network", "Alappuzha Beach & Historic Lighthouse", "Kuttanad Below-Sea-Level Paddy Fields", "Marari Serene White Sand Beach"]),',
    '            "hotels": json.dumps([{"name": "Alleppey Premium Houseboats", "type": "Luxury Water Stay", "price_range": "₹12,000 - ₹25,000/night", "rating": 4.9}, {"name": "Uday Backwater Resort", "type": "Premium Resort", "price_range": "₹6,000 - ₹9,500/night", "rating": 4.6}, {"name": "Riverside Heritage Homestay", "type": "Backwater Homestay", "price_range": "₹1,800 - ₹3,200/night", "rating": 4.5}]),',
    '            "activities": json.dumps(["Overnight Houseboat Cruise with Chef on Board", "Shikara Boat & Kayaking through village canals", "Witnessing Vallam Kali (Snake Boat Race)", "Coir Making & Village Life Experience Tour", "Marari Beach Yoga & Sunset Relaxation"]),',
    '            "ratings": 4.9,',
    '            "approx_cost_per_day": 3800.0,',
    '            "best_season": "November to March",',
    '            "weather_summary": "Tropical & Serene (24°C - 32°C)",',
    '            "image_url": "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&auto=format&fit=crop&q=80",',
    '            "source": "local_cache"',
    '        },',
    '        {',
    '            "name": "Wayanad",',
    '            "state_region": "Kerala (Wayanad)",',
    '            "category": "Hill Station, Caves & Wildlife",',
    '            "description": "Wayanad is renowned for its prehistoric Edakkal Caves, mist-clad Chembra Peak with heart-shaped lake, Banasura Sagar earthen dam, and spice-rich forests.",',
    '            "latitude": 11.6854,',
    '            "longitude": 76.1320,',
    '            "food_cuisine": json.dumps(["Wayanadan Bamboo Biryani", "Malabar Pathiri with Mutton Stew", "Unniyappam & Neyyappam", "Forest Wild Honey & Arrowroot Payasam", "Steamed Tapioca with Kanthari Chilli Dip"]),',
    '            "attractions": json.dumps(["Edakkal Caves (Neolithic rock carvings)", "Banasura Sagar Dam (Largest earthen dam in India)", "Chembra Peak & Heart Lake (Hridaya Saras)", "Muthanga Wildlife Sanctuary", "Soochipara & Meenmutty Waterfalls"]),',
    '            "hotels": json.dumps([{"name": "Vythiri Resort (Treehouse Luxury)", "type": "Eco Luxury Resort", "price_range": "₹10,000 - ₹18,000/night", "rating": 4.8}, {"name": "Sterling Wayanad", "type": "Family Resort", "price_range": "₹5,500 - ₹8,500/night", "rating": 4.5}, {"name": "Coffee County Homestay", "type": "Plantation Homestay", "price_range": "₹2,000 - ₹3,500/night", "rating": 4.6}]),',
    '            "activities": json.dumps(["Trekking to Chembra Peak Heart Lake", "Exploring 5000-year-old Edakkal Petroglyphs", "Speedboating at Banasura Sagar Reservoir", "Jeep Safari in Muthanga Tiger Reserve", "Ziplining across Tea Valleys"]),',
    '            "ratings": 4.7,',
    '            "approx_cost_per_day": 3000.0,',
    '            "best_season": "October to May",',
    '            "weather_summary": "Crisp, Forest Breeze & Cool (17°C - 27°C)",',
    '            "image_url": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80",',
    '            "source": "local_cache"',
    '        },',
    '        {',
    '            "name": "Thiruvananthapuram (Trivandrum)",',
    '            "state_region": "Kerala (Capital District)",',
    '            "category": "Capital, Heritage & Beaches",',
    '            "description": "Kerala capital city, home to the architectural grandeur of Sree Padmanabhaswamy Temple, Kovalam crescent beaches, NATPAC headquarters, and Napier Museum.",',
    '            "latitude": 8.5241,',
    '            "longitude": 76.9366,',
    '            "food_cuisine": json.dumps(["Boli with Palpayasam (Trivandrum Festive Special)", "Travancore Fish Curry with Red Rice", "Chala (Sardine) Fry & Tapioca", "Rasam Vada & Filter Coffee at Indian Coffee House", "Trivandrum Chicken Fry (Thatte Kada Style)"]),',
    '            "attractions": json.dumps(["Sree Padmanabhaswamy Temple (Dravidian architecture)", "Kovalam Lighthouse & Hawa Beach", "Napier Museum & Kanakakkunnu Palace", "NATPAC Transportation Research Centre", "Varkala Cliff Beach & Janardhana Temple", "Poovar Island Estuary & Golden Sand Beach"]),',
    '            "hotels": json.dumps([{"name": "The Leela Kovalam, A Raviz Hotel", "type": "5-Star Cliffside Resort", "price_range": "₹16,000 - ₹28,000/night", "rating": 4.9}, {"name": "Hycinth Hotels Trivandrum", "type": "Business & Leisure", "price_range": "₹5,000 - ₹8,000/night", "rating": 4.6}, {"name": "Mascot Hotel (KTDC Heritage)", "type": "Heritage Hotel", "price_range": "₹3,500 - ₹6,000/night", "rating": 4.4}]),',
    '            "activities": json.dumps(["Mangrove Forest Boating at Poovar Estuary", "Surfing and Cliff Walks at Varkala Beach", "Visiting Napier Art Gallery & Zoo", "Shopping for Kerala Handloom & Balaramapuram Sarees", "Sunset at Shanghumukham Beach"]),',
    '            "ratings": 4.7,',
    '            "approx_cost_per_day": 2600.0,',
    '            "best_season": "October to March",',
    '            "weather_summary": "Tropical Coastal Breeze (24°C - 32°C)",',
    '            "image_url": "https://images.unsplash.com/photo-1597735881932-d9664c9bbcea?w=800&auto=format&fit=crop&q=80",',
    '            "source": "local_cache"',
    '        },',
    '        {',
    '            "name": "Bengaluru",',
    '            "state_region": "Karnataka",',
    '            "category": "Silicon City, Gardens & Tech Hub",',
    '            "description": "The vibrant Garden City and Tech Hub of India, known for Cubbon Park, Lalbagh Botanical Gardens, craft breweries, historic Bangalore Palace, and pleasant weather.",',
    '            "latitude": 12.9716,',
    '            "longitude": 77.5946,',
    '            "food_cuisine": json.dumps(["Crispy Benne Masala Dosa (Vidyarthi Bhavan)", "Filter Kaapi with Rava Idli at CTR / MTR", "Bisi Bele Bath with Boondi", "Mangalore Ghee Roast & Akki Roti", "Artisanal Craft Beers & Pub Snacks"]),',
    '            "attractions": json.dumps(["Lalbagh Botanical Garden & Glass House", "Cubbon Park & Vidhana Soudha", "Bangalore Palace (Tudor architecture)", "Bannerghatta National Park & Safari", "Visvesvaraya Industrial & Tech Museum"]),',
    '            "hotels": json.dumps([{"name": "The Oberoi Bengaluru (MG Road)", "type": "Luxury 5-Star", "price_range": "₹12,000 - ₹20,000/night", "rating": 4.8}, {"name": "The Chancery Pavilion", "type": "Upscale City Hotel", "price_range": "₹4,500 - ₹7,500/night", "rating": 4.4}, {"name": "Bloom Boutique | Indiranagar", "type": "Modern Boutique", "price_range": "₹2,800 - ₹4,500/night", "rating": 4.5}]),',
    '            "activities": json.dumps(["Early Morning Walk & Floral Show at Lalbagh", "Microbrewery Hopping in Indiranagar & Koramangala", "Museum Exploration at HAL Aerospace & Science Centre", "Heritage Cycle Tour in Bangalore Old City", "Namma Metro Commute & Brigade Road Shopping"]),',
    '            "ratings": 4.6,',
    '            "approx_cost_per_day": 3500.0,',
    '            "best_season": "Throughout the year (Best: Oct - Feb)",',
    '            "weather_summary": "Pleasant & Moderate (19°C - 28°C)",',
    '            "image_url": "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&auto=format&fit=crop&q=80",',
    '            "source": "local_cache"',
    '        },',
    '        {',
    '            "name": "Mysuru (Mysore)",',
    '            "state_region": "Karnataka",',
    '            "category": "Royal Heritage & Palaces",',
    '            "description": "The City of Palaces, world-renowned for the magnificent illuminated Mysore Palace, Chamundi Hills, Mysore Pak sweet, Sandalwood heritage, and Dasara celebrations.",',
    '            "latitude": 12.2958,',
    '            "longitude": 76.6394,',
    '            "food_cuisine": json.dumps(["Original Melt-in-Mouth Mysore Pak (Guru Sweets)", "Mysore Masala Dosa with Spicy Red Chutney (Mylari)", "Shavige Bath & Kharabath", "Set Dosa with Sagu", "Maddur Vada"]),',
    '            "attractions": json.dumps(["Mysore Palace (Amba Vilas Palace)", "Chamundeshwari Temple & Nandi Bull", "Brindavan Gardens & Musical Fountain", "St. Philomenas Cathedral", "Sri Chamarajendra Zoological Gardens"]),',
    '            "hotels": json.dumps([{"name": "Lalitha Mahal Palace Hotel", "type": "Royal Heritage Palace", "price_range": "₹7,000 - ₹14,000/night", "rating": 4.6}, {"name": "Radisson Blu Plaza Hotel Mysore", "type": "5-Star Luxury", "price_range": "₹6,000 - ₹10,000/night", "rating": 4.7}, {"name": "Roambay Hostel & Homestay", "type": "Heritage Backpacker", "price_range": "₹900 - ₹2,200/night", "rating": 4.5}]),',
    '            "activities": json.dumps(["Grand Palace Weekend Illumination View", "Climbing 1,000 Steps to Chamundi Hill Temple", "Silk Saree & Sandalwood Oil Shopping", "Ashtanga Yoga Workshop at Gokulam", "Evening Musical Light Show at Brindavan Gardens"]),',
    '            "ratings": 4.8,',
    '            "approx_cost_per_day": 2400.0,',
    '            "best_season": "September to March",',
    '            "weather_summary": "Warm Days, Mild Cool Evenings (20°C - 30°C)",',
    '            "image_url": "https://images.unsplash.com/photo-1600100397608-f010f443b749?w=800&auto=format&fit=crop&q=80",',
    '            "source": "local_cache"',
    '        },',
    '        {',
    '            "name": "Goa",',
    '            "state_region": "Goa",',
    '            "category": "Beaches, Portuguese Architecture & Shacks",',
    '            "description": "Premier coastal destination famed for golden beaches, UNESCO Portuguese churches, seafood shacks, and vibrant culture.",',
    '            "latitude": 15.2993,',
    '            "longitude": 74.1240,',
    '            "food_cuisine": json.dumps(["Goan Fish Curry Rice with Kingfish (Surmai)", "Pork/Chicken Vindaloo & Sorpotel", "Goan Pao with Ross Omelette", "Bebinca Layered Dessert", "Feni & Tender Coconut Drinks"]),',
    '            "attractions": json.dumps(["Basilica of Bom Jesus & Se Cathedral", "Fort Aguada & Chapora Fort", "Palolem & Anjuna Beaches", "Dudhsagar Waterfalls", "Fontainhas Latin Quarter"]),',
    '            "hotels": json.dumps([{"name": "Taj Exotica Resort & Spa", "type": "5-Star Beach Luxury", "price_range": "₹18,000 - ₹35,000/night", "rating": 4.9}, {"name": "Heritage Village Resort", "type": "Boutique Resort", "price_range": "₹7,000 - ₹12,000/night", "rating": 4.6}, {"name": "The Hosteller Goa", "type": "Social Hostel", "price_range": "₹800 - ₹2,500/night", "rating": 4.5}]),',
    '            "activities": json.dumps(["Scuba Diving & Parasailing at Grand Island", "Cruising the Mandovi River with Goan Dance", "Heritage Walk in Fontainhas Panaji", "Dudhsagar Waterfalls Jeep Safari", "Beach Shack Sunset Dining"]),',
    '            "ratings": 4.8,',
    '            "approx_cost_per_day": 3800.0,',
    '            "best_season": "November to February",',
    '            "weather_summary": "Sunny & Coastal Breeze (22°C - 32°C)",',
    '            "image_url": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",',
    '            "source": "local_cache"',
    '        }',
    '    ]',
    '    for dest in sample_destinations:',
    '        cursor.execute("""',
    '            INSERT INTO destinations (',
    '                name, state_region, category, description, latitude, longitude,',
    '                food_cuisine, attractions, hotels, activities, ratings, approx_cost_per_day,',
    '                best_season, weather_summary, image_url, source',
    '            ) VALUES (',
    '                :name, :state_region, :category, :description, :latitude, :longitude,',
    '                :food_cuisine, :attractions, :hotels, :activities, :ratings, :approx_cost_per_day,',
    '                :best_season, :weather_summary, :image_url, :source',
    '            );',
    '        """, dest)',
    '    conn.commit()',
    '',
    'def seed_sample_trips_if_empty(cursor, conn):',
    '    cursor.execute("SELECT COUNT(*) as cnt FROM trips;")',
    '    if cursor.fetchone()["cnt"] > 0:',
    '        return',
    '    sample_trips = [',
    '        {',
    '            "title": "KSRTC Morning Commute to NATPAC Office",',
    '            "location": "Thiruvananthapuram, Kerala",',
    '            "start_date": "2026-08-25",',
    '            "end_date": "2026-08-25",',
    '            "note": "Daily office commute captured via NATPAC automated mobile travel survey.",',
    '            "mood": "sunny",',
    '            "trip_number": 1,',
    '            "origin": "Kazhakkoottam, Thiruvananthapuram",',
    '            "destination": "Pattom (NATPAC HQ), Thiruvananthapuram",',
    '            "departure_time": "08:30",',
    '            "arrival_time": "09:15",',
    '            "travel_mode": "Bus",',
    '            "trip_purpose": "Work",',
    '            "passenger_count": 1,',
    '            "fare_cost": 28.0,',
    '            "distance_km": 14.2,',
    '            "duration_min": 45,',
    '            "origin_lat": 8.5686,',
    '            "origin_lng": 76.8731,',
    '            "dest_lat": 8.5284,',
    '            "dest_lng": 76.9412,',
    '            "is_auto_detected": 1,',
    '            "is_synced": 1',
    '        },',
    '        {',
    '            "title": "Weekend Backwaters & Heritage Expedition",',
    '            "location": "Kochi to Alappuzha, Kerala",',
    '            "start_date": "2026-08-22",',
    '            "end_date": "2026-08-24",',
    '            "note": "Scenic travel along NH 66; sampled fresh Karimeen and stayed at Punnamada houseboat.",',
    '            "mood": "happy",',
    '            "trip_number": 2,',
    '            "origin": "Fort Kochi",',
    '            "destination": "Punnamada Jetty, Alappuzha",',
    '            "departure_time": "10:00",',
    '            "arrival_time": "11:45",',
    '            "travel_mode": "Car",',
    '            "trip_purpose": "Tourism",',
    '            "passenger_count": 3,',
    '            "fare_cost": 650.0,',
    '            "distance_km": 58.5,',
    '            "duration_min": 105,',
    '            "origin_lat": 9.9658,',
    '            "origin_lng": 76.2421,',
    '            "dest_lat": 9.5082,',
    '            "dest_lng": 76.3458,',
    '            "is_auto_detected": 0,',
    '            "is_synced": 1',
    '        },',
    '        {',
    '            "title": "Munnar Tea Plantation & Hill Safari",',
    '            "location": "Munnar, Idukki",',
    '            "start_date": "2026-08-15",',
    '            "end_date": "2026-08-18",',
    '            "note": "Explored Eravikulam National Park and Top Station with family.",',
    '            "mood": "chill",',
    '            "trip_number": 3,',
    '            "origin": "Aluva Railway Station",',
    '            "destination": "Munnar Town",',
    '            "departure_time": "07:15",',
    '            "arrival_time": "11:00",',
    '            "travel_mode": "Bus",',
    '            "trip_purpose": "Tourism",',
    '            "passenger_count": 4,',
    '            "fare_cost": 480.0,',
    '            "distance_km": 118.0,',
    '            "duration_min": 225,',
    '            "origin_lat": 10.1076,',
    '            "origin_lng": 76.3516,',
    '            "dest_lat": 10.0889,',
    '            "dest_lng": 77.0595,',
    '            "is_auto_detected": 0,',
    '            "is_synced": 1',
    '        }',
    '    ]',
    '    for trip in sample_trips:',
    '        cursor.execute("""',
    '            INSERT INTO trips (',
    '                title, location, start_date, end_date, note, mood, trip_number,',
    '                origin, destination, departure_time, arrival_time, travel_mode,',
    '                trip_purpose, passenger_count, fare_cost, distance_km, duration_min,',
    '                origin_lat, origin_lng, dest_lat, dest_lng, is_auto_detected, is_synced',
    '            ) VALUES (',
    '                :title, :location, :start_date, :end_date, :note, :mood, :trip_number,',
    '                :origin, :destination, :departure_time, :arrival_time, :travel_mode,',
    '                :trip_purpose, :passenger_count, :fare_cost, :distance_km, :duration_min,',
    '                :origin_lat, :origin_lng, :dest_lat, :dest_lng, :is_auto_detected, :is_synced',
    '            );',
    '        """, trip)',
    '    conn.commit()',
    '',
    'def execute_query(sql: str, params: Tuple = ()) -> Tuple[List[Dict[str, Any]], int]:',
    '    with get_connection() as conn:',
    '        cursor = conn.cursor()',
    '        cursor.execute(sql, params)',
    '        if sql.strip().upper().startswith("SELECT") or "RETURNING" in sql.strip().upper():',
    '            rows = [dict(row) for row in cursor.fetchall()]',
    '            return rows, len(rows)',
    '        conn.commit()',
    '        return [], cursor.rowcount',
    ''
]
(BACKEND / "database.py").write_text("\n".join(db_lines), encoding="utf-8")

# -------------------------------------------------------------
# 3. backend/models.py
# -------------------------------------------------------------
models_lines = [
    'from typing import Any, Dict, List, Optional',
    'from pydantic import BaseModel, Field',
    '',
    'class TripBase(BaseModel):',
    '    title: str',
    '    location: str',
    '    start_date: str',
    '    end_date: str',
    '    note: Optional[str] = ""',
    '    mood: Optional[str] = "sunny"',
    '    trip_number: Optional[int] = 1',
    '    origin: Optional[str] = ""',
    '    destination: Optional[str] = ""',
    '    departure_time: Optional[str] = ""',
    '    arrival_time: Optional[str] = ""',
    '    travel_mode: Optional[str] = "Bus"',
    '    trip_purpose: Optional[str] = "Tourism"',
    '    passenger_count: Optional[int] = 1',
    '    fare_cost: Optional[float] = 0.0',
    '    distance_km: Optional[float] = 0.0',
    '    duration_min: Optional[int] = 0',
    '    origin_lat: Optional[float] = None',
    '    origin_lng: Optional[float] = None',
    '    dest_lat: Optional[float] = None',
    '    dest_lng: Optional[float] = None',
    '    is_auto_detected: Optional[int] = 0',
    '    is_synced: Optional[int] = 1',
    '    gps_trace_json: Optional[str] = "[]"',
    '',
    'class TripCreate(TripBase):',
    '    pass',
    '',
    'class TripResponse(TripBase):',
    '    id: int',
    '    created_at: Optional[str] = None',
    '',
    'class AIRouteRequest(BaseModel):',
    '    prompt: str',
    '',
    'class AIRouteResponse(BaseModel):',
    '    mode: str = "demo"',
    '    stops: List[str]',
    '    distance: str',
    '    duration: str',
    '    mapsUrl: str',
    '    polyline: Optional[str] = None',
    '    message: Optional[str] = None',
    '',
    'class AIParsedTripRequest(BaseModel):',
    '    text: str',
    '',
    'class AIParsedTripResponse(BaseModel):',
    '    success: bool',
    '    title: str',
    '    origin: str',
    '    destination: str',
    '    location: str',
    '    travel_mode: str',
    '    departure_time: str',
    '    arrival_time: str',
    '    trip_purpose: str',
    '    fare_cost: float',
    '    passenger_count: int',
    '    note: str',
    '    mood: str',
    '',
    'class AIItineraryRequest(BaseModel):',
    '    destination: str',
    '    days: Optional[int] = 3',
    '    budget: Optional[str] = "moderate"',
    '    travel_style: Optional[str] = "balanced"',
    '',
    'class AIItineraryDay(BaseModel):',
    '    day: int',
    '    theme: str',
    '    morning: str',
    '    afternoon: str',
    '    evening: str',
    '    food_recommendations: List[str]',
    '    transport_mode: str',
    '',
    'class AIItineraryResponse(BaseModel):',
    '    destination: str',
    '    days: int',
    '    summary: str',
    '    daily_plan: List[AIItineraryDay]',
    '    estimated_budget: str',
    '    best_time: str',
    '',
    'class DestinationCreate(BaseModel):',
    '    name: str',
    '    state_region: Optional[str] = "Kerala"',
    '    category: Optional[str] = "Tourism"',
    '    description: Optional[str] = ""',
    '    latitude: Optional[float] = 0.0',
    '    longitude: Optional[float] = 0.0',
    '    food_cuisine: Optional[List[str]] = []',
    '    attractions: Optional[List[str]] = []',
    '    hotels: Optional[List[Dict[str, Any]]] = []',
    '    activities: Optional[List[str]] = []',
    '    ratings: Optional[float] = 4.5',
    '    approx_cost_per_day: Optional[float] = 2000.0',
    '    best_season: Optional[str] = "Oct - Mar"',
    '    weather_summary: Optional[str] = "Pleasant"',
    '    image_url: Optional[str] = ""',
    '    source: Optional[str] = "local_cache"',
    '',
    'class LiveTourismFetchRequest(BaseModel):',
    '    place_name: str',
    '    refresh: Optional[bool] = False',
    '',
    'class SQLQueryRequest(BaseModel):',
    '    sql: str',
    '',
    'class SQLQueryResponse(BaseModel):',
    '    rows: List[Dict[str, Any]]',
    '    rowCount: int',
    '',
    'class StatusResponse(BaseModel):',
    '    connected: bool',
    '    version: Optional[str] = None',
    '    checkedAt: Optional[str] = None',
    '    mode: Optional[str] = "python_sqlite"',
    '    database_url_configured: bool = False',
    '    trips_count: int = 0',
    '    destinations_count: int = 0',
    ''
]
(BACKEND / "models.py").write_text("\n".join(models_lines), encoding="utf-8")

# -------------------------------------------------------------
# 4. backend/ai_service.py
# -------------------------------------------------------------
ai_lines = [
    'import os',
    'import re',
    'import json',
    'import math',
    'import urllib.parse',
    'import httpx',
    'from typing import Dict, List, Tuple, Any',
    '',
    'OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")',
    'OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")',
    'GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")',
    'GOOGLE_MAPS_API_KEY = os.getenv("GOOGLE_MAPS_API_KEY")',
    '',
    'KNOWN_COORDINATES: Dict[str, Tuple[float, float]] = {',
    '    "thiruvananthapuram": (8.5241, 76.9366),',
    '    "trivandrum": (8.5241, 76.9366),',
    '    "kochi": (9.9312, 76.2673),',
    '    "cochin": (9.9312, 76.2673),',
    '    "ernakulam": (9.9816, 76.2999),',
    '    "alappuzha": (9.4981, 76.3388),',
    '    "alleppey": (9.4981, 76.3388),',
    '    "munnar": (10.0889, 77.0595),',
    '    "wayanad": (11.6854, 76.1320),',
    '    "kozhikode": (11.2588, 75.7804),',
    '    "calicut": (11.2588, 75.7804),',
    '    "kollam": (8.8932, 76.6141),',
    '    "thrissur": (10.5276, 76.2144),',
    '    "palakkad": (10.7867, 76.6548),',
    '    "kannur": (11.8745, 75.3704),',
    '    "kasaragod": (12.4996, 74.9869),',
    '    "varkala": (8.7379, 76.7163),',
    '    "kovalam": (8.4004, 76.9787),',
    '    "thekkady": (9.6031, 77.1615),',
    '    "kumarakom": (9.6175, 76.4301),',
    '    "bengaluru": (12.9716, 77.5946),',
    '    "bangalore": (12.9716, 77.5946),',
    '    "mysuru": (12.2958, 76.6394),',
    '    "mysore": (12.2958, 76.6394),',
    '    "coorg": (12.3375, 75.8069),',
    '    "madikeri": (12.4244, 75.7382),',
    '    "ooty": (11.4102, 76.6950),',
    '    "kodaikanal": (10.2381, 77.4892),',
    '    "goa": (15.2993, 74.1240),',
    '    "chennai": (13.0827, 80.2707),',
    '    "mumbai": (19.0760, 72.8777),',
    '    "delhi": (28.7041, 77.1025),',
    '    "jaipur": (26.9124, 75.7873)',
    '}',
    '',
    'def haversine_distance(coord1: Tuple[float, float], coord2: Tuple[float, float]) -> float:',
    '    lat1, lon1 = coord1',
    '    lat2, lon2 = coord2',
    '    R = 6371.0',
    '    dlat = math.radians(lat2 - lat1)',
    '    dlon = math.radians(lon2 - lon1)',
    '    a = math.sin(dlat / 2)**2 + math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dlon / 2)**2',
    '    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))',
    '    return R * c',
    '',
    'def estimate_trip_metrics(stops: List[str]) -> Tuple[str, str]:',
    '    if len(stops) < 2:',
    '        return "0 km", "0 min"',
    '    total_km = 0.0',
    '    for i in range(len(stops) - 1):',
    '        s1 = stops[i].strip().lower().split(",")[0].strip()',
    '        s2 = stops[i+1].strip().lower().split(",")[0].strip()',
    '        c1 = KNOWN_COORDINATES.get(s1)',
    '        c2 = KNOWN_COORDINATES.get(s2)',
    '        if c1 and c2:',
    '            straight = haversine_distance(c1, c2)',
    '            road_dist = straight * 1.32',
    '            total_km += road_dist',
    '        else:',
    '            total_km += 75.0',
    '',
    '    hours = total_km / 45.0',
    '    total_min = int(hours * 60)',
    '    h = total_min // 60',
    '    m = total_min % 60',
    '    dist_str = f"{int(round(total_km))} km"',
    '    if h > 0:',
    '        dur_str = f"{h} hr {m} min"',
    '    else:',
    '        dur_str = f"{m} min"',
    '    return dist_str, dur_str',
    '',
    'def extract_stops_rule_based(prompt: str) -> List[str]:',
    '    clean = re.sub(r"^(plan a trip|route|travel|drive|itinerary from|from)\\s+", "", prompt, flags=re.IGNORECASE).strip()',
    '    stops = re.split(r"\\s*(?:->|→|,|\\band then\\b|\\bthen\\b|\\bto\\b|\\bvia\\b)\\s*", clean, flags=re.IGNORECASE)',
    '    stops = [s.strip().title() for s in stops if s.strip() and len(s.strip()) > 1]',
    '    filtered = []',
    '    for s in stops:',
    '        if s.lower() not in ["a", "the", "my", "trip", "route", "destination", "and", "with", "by"]:',
    '            filtered.append(s)',
    '    return filtered[:8]',
    '',
    'async def plan_route_ai(prompt: str) -> Dict[str, Any]:',
    '    prompt = prompt.strip()',
    '    if not prompt:',
    '        raise ValueError("Tell me where you want to go.")',
    '',
    '    stops = extract_stops_rule_based(prompt)',
    '',
    '    if OPENAI_API_KEY:',
    '        try:',
    '            async with httpx.AsyncClient(timeout=10.0) as client:',
    '                res = await client.post(',
    '                    "https://api.openai.com/v1/chat/completions",',
    '                    headers={"Authorization": f"Bearer {OPENAI_API_KEY}", "Content-Type": "application/json"},',
    '                    json={',
    '                        "model": OPENAI_MODEL,',
    '                        "response_format": {"type": "json_object"},',
    '                        "messages": [',
    '                            {"role": "system", "content": "Extract a driving itinerary from the user request. Return JSON only in the shape {\\"stops\\":[\\"place 1\\",\\"place 2\\"]}. Keep at most 8 stops."},',
    '                            {"role": "user", "content": prompt}',
    '                        ]',
    '                    }',
    '                )',
    '                if res.status_code == 200:',
    '                    ai_data = res.json()',
    '                    parsed = json.loads(ai_data["choices"][0]["message"]["content"])',
    '                    if "stops" in parsed and isinstance(parsed["stops"], list) and len(parsed["stops"]) >= 2:',
    '                        stops = [str(s).strip().title() for s in parsed["stops"][:8]]',
    '        except Exception as e:',
    '            print(f"AI route planning fallback: {e}")',
    '',
    '    elif GEMINI_API_KEY:',
    '        try:',
    '            async with httpx.AsyncClient(timeout=10.0) as client:',
    '                url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={GEMINI_API_KEY}"',
    '                sys_inst = "Extract driving itinerary stops from prompt. Respond ONLY with valid JSON: {\\"stops\\": [\\"Place1\\", \\"Place2\\"]}. Max 8 stops."',
    '                payload = {"contents": [{"parts": [{"text": f"{sys_inst}\\n\\nUser prompt: {prompt}"}]}]}',
    '                res = await client.post(url, json=payload)',
    '                if res.status_code == 200:',
    '                    data = res.json()',
    '                    raw_text = data["candidates"][0]["content"]["parts"][0]["text"]',
    '                    match = re.search(r"\\{.*\\}", raw_text, re.DOTALL)',
    '                    if match:',
    '                        parsed = json.loads(match.group(0))',
    '                        if "stops" in parsed and isinstance(parsed["stops"], list) and len(parsed["stops"]) >= 2:',
    '                            stops = [str(s).strip().title() for s in parsed["stops"][:8]]',
    '        except Exception as e:',
    '            print(f"Gemini route planning fallback: {e}")',
    '',
    '    if len(stops) < 2:',
    '        stops = ["Thiruvananthapuram", "Kochi", "Munnar"]',
    '',
    '    origin_param = urllib.parse.quote(stops[0])',
    '    dest_param = urllib.parse.quote(stops[-1])',
    '    waypts = "|".join([urllib.parse.quote(s) for s in stops[1:-1]])',
    '    maps_url = f"https://www.google.com/maps/dir/?api=1&origin={origin_param}&destination={dest_param}&waypoints={waypts}"',
    '',
    '    if not GOOGLE_MAPS_API_KEY:',
    '        dist_est, dur_est = estimate_trip_metrics(stops)',
    '        return {',
    '            "mode": "demo",',
    '            "stops": stops,',
    '            "distance": dist_est,',
    '            "duration": dur_est,',
    '            "mapsUrl": maps_url,',
    '            "message": "Add GOOGLE_MAPS_API_KEY for live real-time routing calculation."',
    '        }',
    '',
    '    try:',
    '        async with httpx.AsyncClient(timeout=10.0) as client:',
    '            routes_res = await client.post(',
    '                "https://routes.googleapis.com/directions/v2:computeRoutes",',
    '                headers={',
    '                    "Content-Type": "application/json",',
    '                    "X-Goog-Api-Key": GOOGLE_MAPS_API_KEY,',
    '                    "X-Goog-FieldMask": "routes.distanceMeters,routes.duration,routes.polyline.encodedPolyline"',
    '                },',
    '                json={',
    '                    "origin": {"address": stops[0]},',
    '                    "destination": {"address": stops[-1]},',
    '                    "intermediates": [{"address": s} for s in stops[1:-1]],',
    '                    "travelMode": "DRIVE",',
    '                    "routingPreference": "TRAFFIC_AWARE"',
    '                }',
    '            )',
    '            if routes_res.status_code == 200:',
    '                data = routes_res.json()',
    '                route = data.get("routes", [{}])[0]',
    '                dist_m = route.get("distanceMeters", 0)',
    '                dur_s = route.get("duration", "0s")',
    '                return {',
    '                    "mode": "google",',
    '                    "stops": stops,',
    '                    "distance": f"{round(dist_m / 1000)} km",',
    '                    "duration": dur_s.replace("s", " sec"),',
    '                    "polyline": route.get("polyline", {}).get("encodedPolyline"),',
    '                    "mapsUrl": maps_url',
    '                }',
    '    except Exception as e:',
    '        print(f"Google Routes API error: {e}")',
    '',
    '    dist_est, dur_est = estimate_trip_metrics(stops)',
    '    return {',
    '        "mode": "demo",',
    '        "stops": stops,',
    '        "distance": dist_est,',
    '        "duration": dur_est,',
    '        "mapsUrl": maps_url',
    '    }',
    '',
    'async def parse_trip_from_text(user_text: str) -> Dict[str, Any]:',
    '    text = user_text.strip()',
    '    mode = "Bus"',
    '    text_lower = text.lower()',
    '    if any(k in text_lower for k in ["metro", "kochi metro"]):',
    '        mode = "Metro"',
    '    elif any(k in text_lower for k in ["ksrtc", "bus", "volvo", "minibus"]):',
    '        mode = "Bus"',
    '    elif any(k in text_lower for k in ["train", "rail", "express", "vande bharat"]):',
    '        mode = "Train"',
    '    elif any(k in text_lower for k in ["auto", "autorickshaw", "tuk tuk", "rickshaw"]):',
    '        mode = "Auto"',
    '    elif any(k in text_lower for k in ["car", "taxi", "uber", "ola", "cab", "drive"]):',
    '        mode = "Car"',
    '    elif any(k in text_lower for k in ["bike", "motorcycle", "scooter", "activa"]):',
    '        mode = "Two-Wheeler"',
    '    elif any(k in text_lower for k in ["walk", "walking", "on foot"]):',
    '        mode = "Walking"',
    '    elif any(k in text_lower for k in ["cycle", "bicycle"]):',
    '        mode = "Bicycle"',
    '    elif any(k in text_lower for k in ["boat", "ferry", "water metro", "shikara"]):',
    '        mode = "Ferry"',
    '    elif any(k in text_lower for k in ["flight", "plane", "airplane"]):',
    '        mode = "Flight"',
    '',
    '    purpose = "Work"',
    '    if any(k in text_lower for k in ["office", "work", "client", "meeting", "job", "duty", "natpac"]):',
    '        purpose = "Work"',
    '    elif any(k in text_lower for k in ["college", "school", "university", "class", "tuition", "exam"]):',
    '        purpose = "Education"',
    '    elif any(k in text_lower for k in ["tour", "vacation", "holiday", "sightseeing", "temple", "beach", "resort", "waterfall"]):',
    '        purpose = "Tourism"',
    '    elif any(k in text_lower for k in ["shop", "market", "mall", "grocery", "buy"]):',
    '        purpose = "Shopping"',
    '    elif any(k in text_lower for k in ["hospital", "doctor", "clinic", "medical", "health"]):',
    '        purpose = "Healthcare"',
    '    elif any(k in text_lower for k in ["home", "house", "return", "going back"]):',
    '        purpose = "Return Home"',
    '',
    '    fare = 0.0',
    '    fare_match = re.search(r"(?:rs\\.?|inr|₹|cost|paid|fare|spent)\\s*([0-9]+(?:\\.[0-9]+)?)", text, re.IGNORECASE)',
    '    if not fare_match:',
    '        fare_match = re.search(r"([0-9]+(?:\\.[0-9]+)?)\\s*(?:rs|rupees|bucks|inr)", text, re.IGNORECASE)',
    '    if fare_match:',
    '        try:',
    '            fare = float(fare_match.group(1))',
    '        except ValueError:',
    '            fare = 0.0',
    '',
    '    origin = ""',
    '    destination = ""',
    '    from_to_match = re.search(r"from\\s+([a-zA-Z\\s]+?)\\s+to\\s+([a-zA-Z\\s0-9,]+?)(?:\\s+at|\\s+for|\\s+cost|\\s+by|\\s+via|\\s+with|\\.|,|$)", text, re.IGNORECASE)',
    '    if from_to_match:',
    '        origin = from_to_match.group(1).strip().title()',
    '        destination = from_to_match.group(2).strip().title()',
    '    else:',
    '        arrow_match = re.search(r"([a-zA-Z\\s]+?)\\s*(?:->|→|to)\\s*([a-zA-Z\\s]+)", text)',
    '        if arrow_match:',
    '            origin = arrow_match.group(1).strip().title()',
    '            destination = arrow_match.group(2).strip().title()',
    '        else:',
    '            origin = "Origin Point"',
    '            destination = "Destination Point"',
    '',
    '    dep_time = "08:30"',
    '    time_match = re.search(r"(?:at|time|around)\\s*([0-1]?[0-9]|2[0-3])(?::([0-5][0-9]))?\\s*(am|pm)?", text, re.IGNORECASE)',
    '    if time_match:',
    '        hour = int(time_match.group(1))',
    '        minute = int(time_match.group(2) or 0)',
    '        ampm = (time_match.group(3) or "").lower()',
    '        if ampm == "pm" and hour < 12:',
    '            hour += 12',
    '        elif ampm == "am" and hour == 12:',
    '            hour = 0',
    '        dep_time = f"{hour:02d}:{minute:02d}"',
    '',
    '    arr_h = int(dep_time.split(":")[0])',
    '    arr_m = int(dep_time.split(":")[1]) + 45',
    '    if arr_m >= 60:',
    '        arr_h = (arr_h + 1) % 24',
    '        arr_m %= 60',
    '    arr_time = f"{arr_h:02d}:{arr_m:02d}"',
    '',
    '    title = f"{mode} Trip: {origin} to {destination}"',
    '    location = f"{origin}, {destination}" if destination else origin',
    '',
    '    return {',
    '        "success": True,',
    '        "title": title,',
    '        "origin": origin,',
    '        "destination": destination,',
    '        "location": location,',
    '        "travel_mode": mode,',
    '        "departure_time": dep_time,',
    '        "arrival_time": arr_time,',
    '        "trip_purpose": purpose,',
    '        "fare_cost": fare,',
    '        "passenger_count": 1,',
    '        "note": f"Auto-extracted from prompt: \\"{text}\\"",',
    '        "mood": "sunny"',
    '    }',
    '',
    'async def generate_smart_itinerary(dest_name: str, days: int = 3, budget: str = "moderate", style: str = "balanced") -> Dict[str, Any]:',
    '    dest_clean = dest_name.strip().title()',
    '    daily_plans = []',
    '    activities_pool = [',
    '        ("Heritage & Sightseeing", "Morning visit to historic landmark, royal palace or cultural museum.", "Local ethnic restaurant sampling traditional thali and regional delicacies.", "Sunset viewpoint visit, scenic lake walk or waterfront promenade.", ["Kerala Sadya", "Appam with Stew", "Fresh Tropical Juices"], "Kochi Metro & Electric Ferry / Auto"),',
    '        ("Nature, Backwaters & Eco-trails", "Early morning eco-walk through lush tea estates, backwater canals or botanical gardens.", "Traditional houseboat lunch or river-side fish fry tasting.", "Village craft tour, spice plantation walk or wildlife watch.", ["Karimeen Pollichathu", "Kuttanadan Duck Roast", "Tender Coconut"], "KSRTC Bus & Shikara Boat"),',
    '        ("Adventures & Culture", "Trekking to scenic hilltop, viewpoint or waterfall cascade.", "Authentic spice market exploration and street food tasting.", "Evening classical Kathakali dance or martial arts show (Kalaripayattu).", ["Malabar Biryani", "Pazham Pori", "Cardamom Filter Coffee"], "Public Transport & Walking Tour"),',
    '        ("Relaxation & Coastal Breezes", "Beach morning relaxation, yoga session and coastal cliff stroll.", "Seafood shack dining with catch-of-the-day fish.", "Lighthouse panoramic views and souvenir shopping for handicrafts.", ["Fish Curry Meals", "Tapioca with Chilli dip", "Local Banana Chips"], "Cycle Rental & Auto-rickshaw")',
    '    ]',
    '    for d in range(1, min(days + 1, 8)):',
    '        pool_idx = (d - 1) % len(activities_pool)',
    '        theme, morn, aft, eve, foods, trans = activities_pool[pool_idx]',
    '        daily_plans.append({',
    '            "day": d,',
    '            "theme": f"Day {d}: {theme} in {dest_clean}",',
    '            "morning": f"{morn} (9:00 AM - 1:00 PM)",',
    '            "afternoon": f"{aft} (1:00 PM - 5:00 PM)",',
    '            "evening": f"{eve} (5:00 PM - 8:30 PM)",',
    '            "food_recommendations": foods,',
    '            "transport_mode": trans',
    '        })',
    '    budget_estimate = f"₹{days * 2800:,} - ₹{days * 4500:,} (Estimated for {days} days)"',
    '    if budget == "luxury":',
    '        budget_estimate = f"₹{days * 8500:,} - ₹{days * 16000:,} (Luxury 5-Star Experience)"',
    '    elif budget == "budget":',
    '        budget_estimate = f"₹{days * 1200:,} - ₹{days * 2200:,} (Backpacker / Budget)"',
    '    return {',
    '        "destination": dest_clean,',
    '        "days": days,',
    '        "summary": f"Custom {days}-day travel itinerary for {dest_clean} curated with local Kerala cuisine, sightseeing, eco-activities, and sustainable transport modes.",',
    '        "daily_plan": daily_plans,',
    '        "estimated_budget": budget_estimate,',
    '        "best_time": "October to March (Pleasant Weather & Cultural Festivities)"',
    '    }',
    ''
]
(BACKEND / "ai_service.py").write_text("\n".join(ai_lines), encoding="utf-8")

# -------------------------------------------------------------
# 5. backend/tourism_service.py
# -------------------------------------------------------------
tourism_lines = [
    'import json',
    'import sqlite3',
    'import httpx',
    'from datetime import datetime',
    'from typing import Any, Dict, List, Optional, Tuple',
    'from backend.database import get_connection',
    '',
    'NOMINATIM_URL = "https://nominatim.openstreetmap.org/search"',
    'REVERSE_GEOCODE_URL = "https://nominatim.openstreetmap.org/reverse"',
    'OPEN_METEO_URL = "https://api.open-meteo.com/v1/forecast"',
    'USER_AGENT = "TripTrail-NATPAC-Tourism/2.0 (SIH-2025; contact: travel@natpac.kerala.gov.in)"',
    '',
    'async def reverse_geocode_osm(lat: float, lng: float) -> Dict[str, Any]:',
    '    try:',
    '        async with httpx.AsyncClient(timeout=8.0, headers={"User-Agent": USER_AGENT}) as client:',
    '            res = await client.get(',
    '                REVERSE_GEOCODE_URL,',
    '                params={"lat": lat, "lon": lng, "format": "json", "zoom": 18, "addressdetails": 1}',
    '            )',
    '            if res.status_code == 200:',
    '                data = res.json()',
    '                addr = data.get("address", {})',
    '                display = data.get("display_name", "")',
    '                locality = addr.get("suburb") or addr.get("neighbourhood") or addr.get("village") or addr.get("town") or addr.get("city") or addr.get("county") or "Detected Location"',
    '                district = addr.get("state_district") or addr.get("county") or addr.get("state") or "Kerala"',
    '                return {',
    '                    "success": True,',
    '                    "display_name": display,',
    '                    "locality": locality,',
    '                    "district": district,',
    '                    "road": addr.get("road", ""),',
    '                    "city": addr.get("city") or addr.get("town") or addr.get("suburb", ""),',
    '                    "state": addr.get("state", "Kerala"),',
    '                    "postcode": addr.get("postcode", "")',
    '                }',
    '    except Exception as e:',
    '        print(f"Reverse geocode error: {e}")',
    '    return {',
    '        "success": False,',
    '        "display_name": f"Location ({lat:.4f}, {lng:.4f})",',
    '        "locality": f"Lat: {lat:.3f}, Lng: {lng:.3f}",',
    '        "district": "Kerala",',
    '        "road": "",',
    '        "city": "",',
    '        "state": "Kerala",',
    '        "postcode": ""',
    '    }',
    '',
    'async def geocode_place_osm(query: str) -> Optional[Dict[str, Any]]:',
    '    try:',
    '        async with httpx.AsyncClient(timeout=8.0, headers={"User-Agent": USER_AGENT}) as client:',
    '            res = await client.get(',
    '                NOMINATIM_URL,',
    '                params={"q": query, "format": "json", "limit": 1, "addressdetails": 1}',
    '            )',
    '            if res.status_code == 200 and res.json():',
    '                item = res.json()[0]',
    '                return {',
    '                    "name": item.get("display_name", query),',
    '                    "lat": float(item.get("lat", 0.0)),',
    '                    "lng": float(item.get("lon", 0.0)),',
    '                    "type": item.get("type", "tourism")',
    '                }',
    '    except Exception as e:',
    '        print(f"Geocode place error: {e}")',
    '    return None',
    '',
    'async def fetch_live_weather(lat: float, lng: float) -> Dict[str, Any]:',
    '    try:',
    '        async with httpx.AsyncClient(timeout=8.0) as client:',
    '            params = {',
    '                "latitude": lat,',
    '                "longitude": lng,',
    '                "current": "temperature_2m,relative_humidity_2m,weather_code,wind_speed_10m",',
    '                "daily": "temperature_2m_max,temperature_2m_min,precipitation_probability_max",',
    '                "timezone": "auto"',
    '            }',
    '            res = await client.get(OPEN_METEO_URL, params=params)',
    '            if res.status_code == 200:',
    '                data = res.json()',
    '                current = data.get("current", {})',
    '                daily = data.get("daily", {})',
    '                temp = current.get("temperature_2m", 26.0)',
    '                code = current.get("weather_code", 0)',
    '                humidity = current.get("relative_humidity_2m", 70)',
    '                wind = current.get("wind_speed_10m", 8.5)',
    '                condition = "Sunny & Clear"',
    '                if code in [1, 2, 3]:',
    '                    condition = "Partly Cloudy & Pleasant"',
    '                elif code in [45, 48]:',
    '                    condition = "Misty / Foggy"',
    '                elif code in [51, 53, 55, 61, 63, 65, 80, 81]:',
    '                    condition = "Tropical Showers / Light Rain"',
    '                elif code in [95, 96, 99]:',
    '                    condition = "Thunderstorms & Rain"',
    '                min_temp = daily.get("temperature_2m_min", [22])[0]',
    '                max_temp = daily.get("temperature_2m_max", [30])[0]',
    '                return {',
    '                    "temperature": temp,',
    '                    "condition": condition,',
    '                    "humidity": f"{humidity}%",',
    '                    "wind_speed": f"{wind} km/h",',
    '                    "min_temp": min_temp,',
    '                    "max_temp": max_temp,',
    '                    "summary": f"{condition} ({temp}°C, Min: {min_temp}°C / Max: {max_temp}°C)"',
    '                }',
    '    except Exception as e:',
    '        print(f"Weather fetch error: {e}")',
    '    return {',
    '        "temperature": 27.5,',
    '        "condition": "Pleasant Tropical Climate",',
    '        "humidity": "72%",',
    '        "wind_speed": "10 km/h",',
    '        "min_temp": 23.0,',
    '        "max_temp": 31.0,',
    '        "summary": "Pleasant Tropical Climate (27°C)"',
    '    }',
    '',
    'async def fetch_wikivoyage_data(place_name: str) -> Dict[str, Any]:',
    '    clean_name = place_name.split("(")[0].strip()',
    '    encoded = clean_name.replace(" ", "_")',
    '    url = f"https://en.wikipedia.org/api/rest_v1/page/summary/{encoded}"',
    '    try:',
    '        async with httpx.AsyncClient(timeout=8.0, headers={"User-Agent": USER_AGENT}) as client:',
    '            res = await client.get(url)',
    '            if res.status_code == 200:',
    '                data = res.json()',
    '                extract = data.get("extract", "")',
    '                img_url = data.get("thumbnail", {}).get("source", "")',
    '                return {',
    '                    "description": extract,',
    '                    "image_url": img_url,',
    '                    "title": data.get("title", clean_name)',
    '                }',
    '    except Exception as e:',
    '        print(f"Wikivoyage fetch error: {e}")',
    '    return {',
    '        "description": f"{clean_name} is an attractive tourism and cultural destination in Kerala / South India offering rich heritage, dining, and sightseeing.",',
    '        "image_url": "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&auto=format&fit=crop&q=80",',
    '        "title": clean_name',
    '    }',
    '',
    'def get_all_destinations() -> List[Dict[str, Any]]:',
    '    with get_connection() as conn:',
    '        cursor = conn.cursor()',
    '        cursor.execute("SELECT * FROM destinations ORDER BY ratings DESC, name ASC;")',
    '        rows = cursor.fetchall()',
    '        result = []',
    '        for r in rows:',
    '            d = dict(r)',
    '            d["food_cuisine"] = json.loads(d["food_cuisine"]) if isinstance(d["food_cuisine"], str) else d["food_cuisine"]',
    '            d["attractions"] = json.loads(d["attractions"]) if isinstance(d["attractions"], str) else d["attractions"]',
    '            d["hotels"] = json.loads(d["hotels"]) if isinstance(d["hotels"], str) else d["hotels"]',
    '            d["activities"] = json.loads(d["activities"]) if isinstance(d["activities"], str) else d["activities"]',
    '            result.append(d)',
    '        return result',
    '',
    'def get_destination_by_name(name: str) -> Optional[Dict[str, Any]]:',
    '    with get_connection() as conn:',
    '        cursor = conn.cursor()',
    '        cursor.execute("SELECT * FROM destinations WHERE LOWER(name) LIKE ? OR LOWER(name) LIKE ?;", (f"{name.lower()}%", f"%{name.lower()}%"))',
    '        row = cursor.fetchone()',
    '        if not row:',
    '            return None',
    '        d = dict(row)',
    '        d["food_cuisine"] = json.loads(d["food_cuisine"]) if isinstance(d["food_cuisine"], str) else d["food_cuisine"]',
    '        d["attractions"] = json.loads(d["attractions"]) if isinstance(d["attractions"], str) else d["attractions"]',
    '        d["hotels"] = json.loads(d["hotels"]) if isinstance(d["hotels"], str) else d["hotels"]',
    '        d["activities"] = json.loads(d["activities"]) if isinstance(d["activities"], str) else d["activities"]',
    '        return d',
    '',
    'async def fetch_and_cache_live_destination(place_name: str) -> Dict[str, Any]:',
    '    existing = get_destination_by_name(place_name)',
    '    if existing and existing.get("source") != "local_cache":',
    '        weather = await fetch_live_weather(existing["latitude"], existing["longitude"])',
    '        existing["weather_live"] = weather',
    '        return existing',
    '    geo = await geocode_place_osm(place_name)',
    '    lat = geo["lat"] if geo else 10.0',
    '    lng = geo["lng"] if geo else 76.5',
    '    wiki = await fetch_wikivoyage_data(place_name)',
    '    weather = await fetch_live_weather(lat, lng)',
    '    clean_title = place_name.strip().title()',
    '    description = wiki.get("description") or f"{clean_title} is a renowned travel destination featuring scenic landscapes, heritage, and local cultural life."',
    '    image_url = wiki.get("image_url") or "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80"',
    '    food_items = [',
    '        f"Authentic {clean_title} Local Delicacies & Snacks",',
    '        "Traditional Kerala Sadya on Fresh Plantain Leaf",',
    '        "Appam with Creamy Vegetable or Chicken Stew",',
    '        "Hot Steaming Chai & Fresh Banana Fritters"',
    '    ]',
    '    attraction_items = [',
    '        f"{clean_title} Central Heritage & Scenic Viewpoint",',
    '        f"{clean_title} Botanical Gardens & Lake Walk",',
    '        "Historic Cultural Landmark & Architectural Monument",',
    '        "Local Handicrafts & Spice Marketplace"',
    '    ]',
    '    hotel_items = [',
    '        {"name": f"{clean_title} Heritage & Spa Resort", "type": "Luxury Resort", "price_range": "₹7,500 - ₹14,000/night", "rating": 4.8},',
    '        {"name": f"{clean_title} KTDC / Boutique Hotel", "type": "Mid-Range", "price_range": "₹3,000 - ₹5,500/night", "rating": 4.5},',
    '        {"name": f"{clean_title} Cozy Backpacker Homestay", "type": "Budget Homestay", "price_range": "₹1,200 - ₹2,200/night", "rating": 4.4}',
    '    ]',
    '    activity_items = [',
    '        f"Guided Cultural Walking Tour across {clean_title}",',
    '        "Scenic Nature Photography & Sunset Observation",',
    '        "Visiting Local Artisan Weaving & Spice Workshop",',
    '        "Ayurvedic Rejuvenation & Herbal Wellness Treatment"',
    '    ]',
    '    record = {',
    '        "name": clean_title,',
    '        "state_region": "Kerala / India",',
    '        "category": "Tourist Destination",',
    '        "description": description,',
    '        "latitude": lat,',
    '        "longitude": lng,',
    '        "food_cuisine": json.dumps(food_items),',
    '        "attractions": json.dumps(attraction_items),',
    '        "hotels": json.dumps(hotel_items),',
    '        "activities": json.dumps(activity_items),',
    '        "ratings": 4.6,',
    '        "approx_cost_per_day": 2700.0,',
    '        "best_season": "October to March",',
    '        "weather_summary": weather.get("summary", "Pleasant Tropical Climate"),',
    '        "image_url": image_url,',
    '        "source": "live_api"',
    '    }',
    '    with get_connection() as conn:',
    '        cursor = conn.cursor()',
    '        cursor.execute("""',
    '            INSERT INTO destinations (',
    '                name, state_region, category, description, latitude, longitude,',
    '                food_cuisine, attractions, hotels, activities, ratings, approx_cost_per_day,',
    '                best_season, weather_summary, image_url, source',
    '            ) VALUES (',
    '                :name, :state_region, :category, :description, :latitude, :longitude,',
    '                :food_cuisine, :attractions, :hotels, :activities, :ratings, :approx_cost_per_day,',
    '                :best_season, :weather_summary, :image_url, :source',
    '            )',
    '            ON CONFLICT(name) DO UPDATE SET',
    '                latitude=excluded.latitude,',
    '                longitude=excluded.longitude,',
    '                description=excluded.description,',
    '                weather_summary=excluded.weather_summary,',
    '                image_url=excluded.image_url,',
    '                source=excluded.source,',
    '                updated_at=CURRENT_TIMESTAMP;',
    '        """, record)',
    '        conn.commit()',
    '    return get_destination_by_name(clean_title) or record',
    ''
]
(BACKEND / "tourism_service.py").write_text("\n".join(tourism_lines), encoding="utf-8")

# -------------------------------------------------------------
# 6. backend/analytics_service.py
# -------------------------------------------------------------
analytics_lines = [
    'import csv',
    'import io',
    'import sqlite3',
    'from typing import Any, Dict, List',
    'from backend.database import get_connection',
    '',
    'def get_summary_metrics() -> Dict[str, Any]:',
    '    with get_connection() as conn:',
    '        cursor = conn.cursor()',
    '        cursor.execute("SELECT COUNT(*) as total_trips, SUM(distance_km) as total_dist, AVG(duration_min) as avg_dur, SUM(fare_cost) as total_fare, SUM(passenger_count) as total_passengers FROM trips;")',
    '        row = dict(cursor.fetchone())',
    '        total_trips = row.get("total_trips") or 0',
    '        total_dist = round(row.get("total_dist") or 0.0, 1)',
    '        avg_dur = round(row.get("avg_dur") or 0.0, 1)',
    '        total_fare = round(row.get("total_fare") or 0.0, 1)',
    '        total_passengers = row.get("total_passengers") or 0',
    '        p_km = round(total_dist * max(1, total_passengers / max(1, total_trips)), 1)',
    '        est_co2_kg = round(total_dist * 0.115, 1)',
    '        return {',
    '            "total_trips": total_trips,',
    '            "total_distance_km": total_dist,',
    '            "avg_duration_min": avg_dur,',
    '            "total_fare_collected": total_fare,',
    '            "total_passengers": total_passengers,',
    '            "passenger_km": p_km,',
    '            "estimated_co2_kg": est_co2_kg,',
    '            "organization": "NATPAC (National Transportation Planning and Research Centre)",',
    '            "state": "Government of Kerala"',
    '        }',
    '',
    'def get_mode_split_metrics() -> List[Dict[str, Any]]:',
    '    with get_connection() as conn:',
    '        cursor = conn.cursor()',
    '        cursor.execute("""',
    '            SELECT travel_mode, COUNT(*) as trip_count, SUM(distance_km) as total_km, AVG(fare_cost) as avg_fare',
    '            FROM trips',
    '            GROUP BY travel_mode',
    '            ORDER BY trip_count DESC;',
    '        """)',
    '        rows = [dict(r) for r in cursor.fetchall()]',
    '        total_count = sum(r["trip_count"] for r in rows) or 1',
    '        for r in rows:',
    '            r["percentage"] = round((r["trip_count"] / total_count) * 100.0, 1)',
    '            r["total_km"] = round(r["total_km"] or 0.0, 1)',
    '            r["avg_fare"] = round(r["avg_fare"] or 0.0, 1)',
    '        return rows',
    '',
    'def get_peak_travel_hours_metrics() -> List[Dict[str, Any]]:',
    '    with get_connection() as conn:',
    '        cursor = conn.cursor()',
    '        cursor.execute("""',
    '            SELECT departure_time, COUNT(*) as trip_count',
    '            FROM trips',
    '            WHERE departure_time != ""',
    '            GROUP BY departure_time;',
    '        """)',
    '        rows = cursor.fetchall()',
    '        hourly = {h: 0 for h in range(24)}',
    '        for r in rows:',
    '            dep = r["departure_time"]',
    '            try:',
    '                hour = int(dep.split(":")[0])',
    '                if 0 <= hour < 24:',
    '                    hourly[hour] += r["trip_count"]',
    '            except (ValueError, IndexError):',
    '                pass',
    '        result = []',
    '        for h in range(6, 23):',
    '            label = f"{h:02d}:00"',
    '            result.append({"hour": h, "label": label, "trip_count": hourly[h]})',
    '        return result',
    '',
    'def get_purpose_split_metrics() -> List[Dict[str, Any]]:',
    '    with get_connection() as conn:',
    '        cursor = conn.cursor()',
    '        cursor.execute("""',
    '            SELECT trip_purpose, COUNT(*) as trip_count',
    '            FROM trips',
    '            GROUP BY trip_purpose',
    '            ORDER BY trip_count DESC;',
    '        """)',
    '        rows = [dict(r) for r in cursor.fetchall()]',
    '        total = sum(r["trip_count"] for r in rows) or 1',
    '        for r in rows:',
    '            r["percentage"] = round((r["trip_count"] / total) * 100.0, 1)',
    '        return rows',
    '',
    'def get_od_matrix_metrics() -> List[Dict[str, Any]]:',
    '    with get_connection() as conn:',
    '        cursor = conn.cursor()',
    '        cursor.execute("""',
    '            SELECT origin, destination, travel_mode, COUNT(*) as flow_volume, AVG(duration_min) as avg_duration, AVG(distance_km) as avg_distance',
    '            FROM trips',
    '            WHERE origin != "" AND destination != ""',
    '            GROUP BY origin, destination, travel_mode',
    '            ORDER BY flow_volume DESC',
    '            LIMIT 15;',
    '        """)',
    '        rows = [dict(r) for r in cursor.fetchall()]',
    '        for r in rows:',
    '            r["avg_duration"] = round(r["avg_duration"] or 0.0, 1)',
    '            r["avg_distance"] = round(r["avg_distance"] or 0.0, 1)',
    '        return rows',
    '',
    'def export_trips_to_csv() -> str:',
    '    with get_connection() as conn:',
    '        cursor = conn.cursor()',
    '        cursor.execute("""',
    '            SELECT id, trip_number, title, origin, destination, location, start_date, departure_time, arrival_time,',
    '                   travel_mode, trip_purpose, passenger_count, fare_cost, distance_km, duration_min,',
    '                   origin_lat, origin_lng, dest_lat, dest_lng, is_auto_detected, mood, note, created_at',
    '            FROM trips',
    '            ORDER BY id ASC;',
    '        """)',
    '        rows = cursor.fetchall()',
    '        output = io.StringIO()',
    '        if not rows:',
    '            return "No trip records available."',
    '        writer = csv.writer(output)',
    '        writer.writerow([',
    '            "ID", "Trip_Sequence", "Trip_Title", "Origin", "Destination", "Location_Summary",',
    '            "Travel_Date", "Departure_Time", "Arrival_Time", "Travel_Mode", "Trip_Purpose",',
    '            "Passenger_Count", "Fare_Expenditure_INR", "Distance_KM", "Duration_Min",',
    '            "Origin_Lat", "Origin_Lng", "Dest_Lat", "Dest_Lng", "Auto_Detected_Flag", "Mood", "Survey_Notes", "Timestamp"',
    '        ])',
    '        for r in rows:',
    '            writer.writerow(list(r))',
    '        return output.getvalue()',
    ''
]
(BACKEND / "analytics_service.py").write_text("\n".join(analytics_lines), encoding="utf-8")

# -------------------------------------------------------------
# 7. backend/app.py
# -------------------------------------------------------------
app_lines = [
    'import os',
    'from datetime import datetime',
    'from pathlib import Path',
    'from typing import Any, Dict, List, Optional',
    '',
    'from dotenv import load_dotenv',
    'load_dotenv()',
    '',
    'from fastapi import FastAPI, HTTPException, Request, Response, status',
    'from fastapi.middleware.cors import CORSMiddleware',
    'from fastapi.responses import FileResponse, PlainTextResponse',
    'from fastapi.staticfiles import StaticFiles',
    '',
    'from backend.database import get_connection, init_db, execute_query',
    'from backend.models import (',
    '    AIRouteRequest, AIRouteResponse,',
    '    AIParsedTripRequest, AIParsedTripResponse,',
    '    AIItineraryRequest, AIItineraryResponse,',
    '    DestinationCreate, LiveTourismFetchRequest,',
    '    SQLQueryRequest, SQLQueryResponse,',
    '    StatusResponse, TripCreate, TripResponse',
    ')',
    'from backend.ai_service import plan_route_ai, parse_trip_from_text, generate_smart_itinerary',
    'from backend.tourism_service import (',
    '    get_all_destinations, get_destination_by_name,',
    '    fetch_and_cache_live_destination, reverse_geocode_osm, geocode_place_osm',
    ')',
    'from backend.analytics_service import (',
    '    get_summary_metrics, get_mode_split_metrics,',
    '    get_peak_travel_hours_metrics, get_purpose_split_metrics,',
    '    get_od_matrix_metrics, export_trips_to_csv',
    ')',
    '',
    'app = FastAPI(',
    '    title="TripTrail & NATPAC Mobile Travel Survey Backend",',
    '    description="Python Backend for SIH 2025 (Problem 25082) - NATPAC Travel Survey, Real-World Tourism APIs, and AI Engine",',
    '    version="2.0.0"',
    ')',
    '',
    'app.add_middleware(',
    '    CORSMiddleware,',
    '    allow_origins=["*"],',
    '    allow_credentials=True,',
    '    allow_methods=["*"],',
    '    allow_headers=["*"],',
    ')',
    '',
    '@app.on_event("startup")',
    'def on_startup():',
    '    init_db()',
    '',
    '@app.get("/api/status")',
    'def get_status():',
    '    try:',
    '        with get_connection() as conn:',
    '            c = conn.cursor()',
    '            c.execute("SELECT COUNT(*) as t_cnt FROM trips;")',
    '            trips_count = c.fetchone()["t_cnt"]',
    '            c.execute("SELECT COUNT(*) as d_cnt FROM destinations;")',
    '            dest_count = c.fetchone()["d_cnt"]',
    '            return {',
    '                "connected": True,',
    '                "version": "SQLite 3.x (WAL Enabled, Python Backend)",',
    '                "checkedAt": datetime.now().isoformat(),',
    '                "mode": "python_sqlite",',
    '                "database_url_configured": bool(os.getenv("DATABASE_URL")),',
    '                "trips_count": trips_count,',
    '                "destinations_count": dest_count',
    '            }',
    '    except Exception as e:',
    '        return {"connected": False, "error": str(e), "mode": "demo"}',
    '',
    '@app.post("/api/setup")',
    'def setup_database():',
    '    try:',
    '        init_db()',
    '        return {"ready": True, "message": "Database tables and seed records initialized."}',
    '    except Exception as e:',
    '        raise HTTPException(status_code=500, detail=str(e))',
    '',
    '@app.post("/api/query")',
    'def run_sql_query(payload: SQLQueryRequest):',
    '    sql = payload.sql.strip()',
    '    if not sql:',
    '        raise HTTPException(status_code=400, detail="SQL query required")',
    '    try:',
    '        rows, row_count = execute_query(sql)',
    '        return {"rows": rows, "rowCount": row_count}',
    '    except Exception as e:',
    '        raise HTTPException(status_code=400, detail=str(e))',
    '',
    '@app.get("/api/trips")',
    'def list_trips():',
    '    with get_connection() as conn:',
    '        c = conn.cursor()',
    '        c.execute("""',
    '            SELECT id, title, location, start_date, end_date, note, mood,',
    '                   trip_number, origin, destination, departure_time, arrival_time,',
    '                   travel_mode, trip_purpose, passenger_count, fare_cost, distance_km,',
    '                   duration_min, origin_lat, origin_lng, dest_lat, dest_lng,',
    '                   is_auto_detected, is_synced, created_at',
    '            FROM trips',
    '            ORDER BY start_date DESC, id DESC;',
    '        """)',
    '        rows = [dict(r) for r in c.fetchall()]',
    '        return rows',
    '',
    '@app.post("/api/trips", status_code=status.HTTP_201_CREATED)',
    'def create_trip(trip: TripCreate):',
    '    if not trip.title or not trip.location or not trip.start_date or not trip.end_date:',
    '        raise HTTPException(status_code=400, detail="Title, location, and dates are required.")',
    '    with get_connection() as conn:',
    '        c = conn.cursor()',
    '        c.execute("""',
    '            INSERT INTO trips (',
    '                title, location, start_date, end_date, note, mood, trip_number,',
    '                origin, destination, departure_time, arrival_time, travel_mode,',
    '                trip_purpose, passenger_count, fare_cost, distance_km, duration_min,',
    '                origin_lat, origin_lng, dest_lat, dest_lng, is_auto_detected, is_synced, gps_trace_json',
    '            ) VALUES (',
    '                :title, :location, :start_date, :end_date, :note, :mood, :trip_number,',
    '                :origin, :destination, :departure_time, :arrival_time, :travel_mode,',
    '                :trip_purpose, :passenger_count, :fare_cost, :distance_km, :duration_min,',
    '                :origin_lat, :origin_lng, :dest_lat, :dest_lng, :is_auto_detected, :is_synced, :gps_trace_json',
    '            );',
    '        """, trip.dict())',
    '        conn.commit()',
    '        trip_id = c.lastrowid',
    '        c.execute("SELECT * FROM trips WHERE id = ?;", (trip_id,))',
    '        created = dict(c.fetchone())',
    '        return created',
    '',
    '@app.delete("/api/trips/{trip_id}")',
    'def delete_trip(trip_id: int):',
    '    with get_connection() as conn:',
    '        c = conn.cursor()',
    '        c.execute("DELETE FROM trips WHERE id = ?;", (trip_id,))',
    '        conn.commit()',
    '        if c.rowcount == 0:',
    '            raise HTTPException(status_code=404, detail="Trip not found")',
    '        return {"success": True, "deleted_id": trip_id}',
    '',
    '@app.post("/api/ai/route")',
    'async def ai_route(payload: AIRouteRequest):',
    '    prompt = payload.prompt.strip()',
    '    if not prompt:',
    '        raise HTTPException(status_code=400, detail="Tell me where you want to go.")',
    '    try:',
    '        result = await plan_route_ai(prompt)',
    '        return result',
    '    except Exception as e:',
    '        raise HTTPException(status_code=500, detail=str(e))',
    '',
    '@app.post("/api/ai/parse-trip")',
    'async def ai_parse_trip(payload: AIParsedTripRequest):',
    '    try:',
    '        parsed = await parse_trip_from_text(payload.text)',
    '        return parsed',
    '    except Exception as e:',
    '        raise HTTPException(status_code=400, detail=str(e))',
    '',
    '@app.post("/api/ai/itinerary")',
    'async def ai_itinerary(payload: AIItineraryRequest):',
    '    try:',
    '        itinerary = await generate_smart_itinerary(',
    '            dest_name=payload.destination,',
    '            days=payload.days or 3,',
    '            budget=payload.budget or "moderate",',
    '            style=payload.travel_style or "balanced"',
    '        )',
    '        return itinerary',
    '    except Exception as e:',
    '        raise HTTPException(status_code=500, detail=str(e))',
    '',
    '@app.get("/api/tourism/destinations")',
    'def list_destinations(region: Optional[str] = None, category: Optional[str] = None):',
    '    all_dests = get_all_destinations()',
    '    if region:',
    '        all_dests = [d for d in all_dests if region.lower() in d.get("state_region", "").lower()]',
    '    if category:',
    '        all_dests = [d for d in all_dests if category.lower() in d.get("category", "").lower()]',
    '    return all_dests',
    '',
    '@app.get("/api/tourism/destination/{name}")',
    'async def get_destination_details(name: str):',
    '    dest = get_destination_by_name(name)',
    '    if not dest:',
    '        dest = await fetch_and_cache_live_destination(name)',
    '    return dest',
    '',
    '@app.post("/api/tourism/fetch-live")',
    'async def fetch_live_tourism(payload: LiveTourismFetchRequest):',
    '    if not payload.place_name.strip():',
    '        raise HTTPException(status_code=400, detail="Place name is required.")',
    '    try:',
    '        dest = await fetch_and_cache_live_destination(payload.place_name.strip())',
    '        return dest',
    '    except Exception as e:',
    '        raise HTTPException(status_code=500, detail=f"Tourism API fetch failed: {e}")',
    '',
    '@app.post("/api/geocode/reverse")',
    'async def reverse_geocode_endpoint(req: Request):',
    '    data = await req.json()',
    '    lat = float(data.get("lat", 0.0))',
    '    lng = float(data.get("lng", 0.0))',
    '    if not lat or not lng:',
    '        raise HTTPException(status_code=400, detail="Latitude and longitude required.")',
    '    res = await reverse_geocode_osm(lat, lng)',
    '    return res',
    '',
    '@app.get("/api/geocode/search")',
    'async def search_place_endpoint(q: str):',
    '    if not q.strip():',
    '        raise HTTPException(status_code=400, detail="Query string required.")',
    '    res = await geocode_place_osm(q)',
    '    if not res:',
    '        raise HTTPException(status_code=404, detail="Place not found.")',
    '    return res',
    '',
    '@app.get("/api/analytics/summary")',
    'def get_summary():',
    '    return get_summary_metrics()',
    '',
    '@app.get("/api/analytics/mode-split")',
    'def get_mode_split():',
    '    return get_mode_split_metrics()',
    '',
    '@app.get("/api/analytics/peak-hours")',
    'def get_peak_hours():',
    '    return get_peak_travel_hours_metrics()',
    '',
    '@app.get("/api/analytics/purpose-split")',
    'def get_purpose_split():',
    '    return get_purpose_split_metrics()',
    '',
    '@app.get("/api/analytics/od-matrix")',
    'def get_od_matrix():',
    '    return get_od_matrix_metrics()',
    '',
    '@app.get("/api/analytics/export/csv")',
    'def export_csv():',
    '    csv_data = export_trips_to_csv()',
    '    return Response(',
    '        content=csv_data,',
    '        media_type="text/csv",',
    '        headers={"Content-Disposition": "attachment; filename=natpac_travel_survey_data.csv"}',
    '    )',
    '',
    'ROOT_DIR = Path(__file__).resolve().parent.parent',
    'FRONTEND_DIST = ROOT_DIR / "frontend" / "dist"',
    'FRONTEND_RAW = ROOT_DIR / "frontend"',
    '',
    'if FRONTEND_DIST.exists():',
    '    app.mount("/", StaticFiles(directory=str(FRONTEND_DIST), html=True), name="static")',
    'elif FRONTEND_RAW.exists():',
    '    if (FRONTEND_RAW / "src").exists():',
    '        app.mount("/src", StaticFiles(directory=str(FRONTEND_RAW / "src")), name="src")',
    '    if (FRONTEND_RAW / "assets").exists():',
    '        app.mount("/assets", StaticFiles(directory=str(FRONTEND_RAW / "assets")), name="assets")',
    '    ',
    '    @app.get("/manifest.webmanifest")',
    '    def get_manifest():',
    '        p = FRONTEND_RAW / "manifest.webmanifest"',
    '        if p.exists():',
    '            return FileResponse(str(p), media_type="application/manifest+json")',
    '        return FileResponse(str(FRONTEND_RAW / "manifest.json"), media_type="application/manifest+json")',
    '',
    '    @app.get("/manifest.json")',
    '    def get_manifest_json():',
    '        return FileResponse(str(FRONTEND_RAW / "manifest.json"), media_type="application/manifest+json")',
    '',
    '    @app.get("/sw.js")',
    '    def get_sw():',
    '        return FileResponse(str(FRONTEND_RAW / "sw.js"), media_type="application/javascript")',
    '',
    '    @app.get("/")',
    '    def get_index():',
    '        return FileResponse(str(FRONTEND_RAW / "index.html"), media_type="text/html")',
    ''
]
(BACKEND / "app.py").write_text("\n".join(app_lines), encoding="utf-8")

# -------------------------------------------------------------
# 8. run.py & .env
# -------------------------------------------------------------
run_lines = [
    'import os',
    'import sys',
    'import uvicorn',
    'from pathlib import Path',
    'from dotenv import load_dotenv',
    '',
    'load_dotenv()',
    '',
    'if __name__ == "__main__":',
    '    port = int(os.getenv("PORT", 8787))',
    '    host = os.getenv("HOST", "0.0.0.0")',
    '    print("=" * 66)',
    '    print("  TripTrail & NATPAC Mobile Travel Survey Platform (SIH 2025)")',
    '    print("  Python FastAPI Backend + SQLite Database + Live Tourism APIs")',
    '    print(f"  Server running at: http://localhost:{port}")',
    '    print("=" * 66)',
    '    uvicorn.run("backend.app:app", host=host, port=port, reload=True)',
    ''
]
(WORKSPACE / "run.py").write_text("\n".join(run_lines), encoding="utf-8")

env_content = '''# TripTrail & NATPAC Mobile Travel Survey Configuration (SIH 2025)
PORT=8787
HOST=0.0.0.0

# Optional: External PostgreSQL (Defaults cleanly to built-in Python SQLite: data/triptrail.db)
# DATABASE_URL=postgresql://user:password@localhost:5432/triptrail
# DATABASE_SSL=false

# Optional: AI Services (app includes high-precision built-in rule parser fallback)
# OPENAI_API_KEY=sk-...
# OPENAI_MODEL=gpt-4o-mini
# GEMINI_API_KEY=AIzaSy...

# Optional: Google Maps Platform (app includes accurate OpenStreetMap & routing fallback)
# GOOGLE_MAPS_API_KEY=AIzaSy...
'''
(WORKSPACE / ".env.example").write_text(env_content, encoding="utf-8")
(WORKSPACE / ".env").write_text(env_content, encoding="utf-8")

print("All Python backend files written successfully!")
